Changes provincials
FRC2706/2024-2706-Robot-Code pull request #122
Opened 2024-04-04 03:36 UTC by LuisFerArredondo

## Describe your changes

- [ ] Bug fix
- [ ] New feature

Explain what you did:
> ...

## Issue ticket (add number)

> https://github.com/FRC2706/2024-2706-Robot-Code/issues/...

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] I have tested thoroughly.
- [ ] I have written documentation and explained about my changes to the best of my ability.

2024-04-04 10:30 UTC, weizhang-2706 commented on src/main/java/frc/robot/Config.java
> +  SPEAKER_VISION_SHOT(30.2), // 31.2
My impression with vision shot at the practice field looks good. May not need to be adjusted.

2024-04-29 01:43 UTC, weizhang-2706 requested changes

2024-04-29 01:43 UTC, weizhang-2706 commented on src/main/java/frc/robot/Robot.java
> +    //ShooterSubsystem.getInstance().changeCurrentLimit(true);
cleanup this line

2024-04-29 01:43 UTC, weizhang-2706 commented on src/main/java/frc/robot/Robot.java
> +    //ShooterSubsystem.getInstance().changeCurrentLimit(false);
clean up

2024-04-29 01:43 UTC, weizhang-2706 commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +/*
clean up these lines

2024-05-02 00:03 UTC, ErikCald approved these changes

2024-05-02 00:03 UTC, weizhang-2706 approved these changes

2024-05-02 00:04 UTC, merged