Path planner
FRC2706/2024-2706-Robot-Code pull request #39
Opened 2024-01-27 20:06 UTC by Khalil-Burns

## Describe your changes

- [ ] Bug fix
- [ ] New feature

Explain what you did:
> ...

## Issue ticket (add number)

> https://github.com/FRC2706/2024-2706-Robot-Code/issues/...

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] I have tested thoroughly.
- [ ] I have written documentation and explained about my changes to the best of my ability.

2024-01-30 21:11 UTC, ErikCald approved these changes

2024-01-31 02:02 UTC, weizhang-2706 requested changes

2024-01-31 02:02 UTC, weizhang-2706 commented on src/main/java/frc/robot/robotcontainers/NewRobotContainer.java
> +    return new PathPlannerAuto("testAuto");
put "new PathPlannerAuto...." to case 2 in AutoRoutines.java

2024-01-31 02:02 UTC, weizhang-2706 commented on src/main/java/frc/robot/subsystems/SwerveSubsystem.java
> +            var alliance = DriverStation.getAlliance();
I am wondering how to test this.
Driver station test mode is good for this?

2024-02-01 01:04 UTC, weizhang-2706 approved these changes

2024-02-03 18:01 UTC, merged