changed errRev to configureSpark
FRC2706/2024-2706-Robot-Code pull request #51
Opened 2024-02-08 00:48 UTC by emilycxliu

## Describe your changes

- [ ] Bug fix
- [ ] New feature

Explain what you did:
> ...

## Issue ticket (add number)

> https://github.com/FRC2706/2024-2706-Robot-Code/issues/...

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] I have tested thoroughly.
- [ ] I have written documentation and explained about my changes to the best of my ability.

2024-02-08 01:11 UTC, weizhang-2706 requested changes

2024-02-08 01:11 UTC, weizhang-2706 commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
>        m_arm.setInverted(Config.ArmConfig.SET_INVERTED); //sets movement direction
you can also put this inside configureSpark()

2024-02-10 16:15 UTC, weizhang-2706 approved these changes

2024-02-10 16:18 UTC, emilycxliu commented
since setInverted retruns a void, I can't put it into configureSPark

2024-02-10 18:20 UTC, weizhang-2706 approved these changes

2024-02-10 18:51 UTC, ErikCald approved these changes

2024-02-10 18:51 UTC, merged