Shooter
FRC2706/2024-2706-Robot-Code pull request #56
Opened 2024-02-10 00:56 UTC by LuisFerArredondo

## Describe your changes

- [ ] Bug fix
- [ ] New feature:
 
Explain what you did:
> We created the Shooter Code 

## Issue ticket (add number): 18

> https://github.com/FRC2706/2024-2706-Robot-Code/issues/...

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] I have tested thoroughly.
- [ ] I have written documentation and explained about my changes to the best of my ability.

2024-02-10 01:07 UTC, weizhang-2706 requested changes

2024-02-10 01:07 UTC, weizhang-2706 commented on src/main/java/frc/robot/commands/Shooter_tuner.java
> +  public Shooter_tuner() {
It is better to have an input argument for setpoint.

2024-02-10 01:07 UTC, weizhang-2706 commented on src/main/java/frc/robot/commands/Shooter_tuner.java
> +    shooter.setSetPoint(1000);
instead of hard code here, make a variable for setpoint.

2024-02-10 01:07 UTC, weizhang-2706 commented on src/main/java/frc/robot/subsystems/Intake.java
> +public class Intake extends SubsystemBase {
We already have an intake subsystem for the intake motor.
Could change its name to sensor related.

2024-02-10 01:09 UTC, weizhang-2706 requested changes

2024-02-10 01:09 UTC, weizhang-2706 commented on src/main/java/frc/robot/subsystems/Shooter.java
> +            m_motor = new CANSparkMax(1, MotorType.kBrushless);
We use singleton for each subsystem, which means only one instance for each subsystem. 
You can refer to other subsystem, e.g. intake or climber.

2024-02-14 23:50 UTC, weizhang-2706 requested changes

2024-02-14 23:50 UTC, weizhang-2706 commented on src/main/java/frc/robot/commands/Shooter_tuner.java
> +    shooter = new Shooter();
Need to addRequirements(shooter) here

2024-02-14 23:59 UTC, weizhang-2706 requested changes

2024-02-14 23:59 UTC, weizhang-2706 commented on src/main/java/frc/robot/subsystems/Shooter.java
> +            m_motor = new CANSparkMax(1, MotorType.kBrushless);
change CAN ID to 32.

2024-02-15 00:00 UTC, weizhang-2706 requested changes

2024-02-15 00:00 UTC, weizhang-2706 commented on src/main/java/frc/robot/subsystems/IntakeSensor.java
> +    limitSwitch = new DigitalInput(5);
Change 5 to 7, which is on the robot now.

2024-02-15 00:53 UTC, weizhang-2706 requested changes

2024-02-15 00:53 UTC, weizhang-2706 commented on src/main/java/frc/robot/robotcontainers/NewRobotContainer.java
> +  //private final SwerveSubsystem s_Swerve = SwerveSubsystem.getInstance();
you can clean up this now

2024-02-15 00:57 UTC, weizhang-2706 requested changes

2024-02-15 00:57 UTC, weizhang-2706 commented on src/main/java/frc/robot/robotcontainers/NewRobotContainer.java
> +    /*  Setup default commands
You need to put it back, i.e. uncomment

2024-02-15 00:57 UTC, weizhang-2706 commented on src/main/java/frc/robot/robotcontainers/NewRobotContainer.java
> +    /*driver.start().onTrue(SwerveSubsystem.getInstance().setHeadingCommand(new Rotation2d(0)));
something here is wrong. Need check the other */

2024-02-15 01:08 UTC, weizhang-2706 approved these changes

2024-02-15 01:35 UTC, jogray72 commented
Okay, fix my comments in the next update

2024-02-15 01:36 UTC, jogray72 approved these changes
Thanks.  Looks good, just make the minor updates on the next update.

2024-02-15 01:36 UTC, jogray72 commented on src/main/java/frc/robot/subsystems/IntakeSensor.java
>      limitSwitch = new DigitalInput(5);
Should the 5 use a variable from Config instead....

2024-02-15 01:36 UTC, jogray72 commented on src/main/java/frc/robot/subsystems/IntakeSensor.java
> +    limitSwitch = new DigitalInput(7);
The 7 should use a Variable from config instead of being hard coded

2024-02-15 01:43 UTC, merged