Keira samuel vision testing
FRC2706/2024-2706-Robot-Code pull request #74
Opened 2024-02-22 01:50 UTC by Codingfor1

## Describe your changes

- [ ] Bug fix
- [ ] New feature

Explain what you did:
> ...

## Issue ticket (add number)

> https://github.com/FRC2706/2024-2706-Robot-Code/issues/...

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] I have tested thoroughly.
- [ ] I have written documentation and explained about my changes to the best of my ability.

2024-02-22 01:55 UTC, ErikCald requested changes, later dismissed

2024-02-22 01:55 UTC, ErikCald commented on src/main/java/frc/robot/subsystems/PhotonSubsystem.java
> +      if (range < 6 & range > 1.5){
Use &`& `not `&`. &`& `compares booleans but `& `does a bitwise AND which is unpredictable what it will do in this case.

2024-02-22 01:59 UTC, ErikCald commented on src/main/java/frc/robot/subsystems/PhotonSubsystem.java
> +      if (range < 6 & range > 1.5){
bitwise AND might technically work but its not a good practice. Ideally use `&&`

2024-02-25 22:07 UTC, ErikCald approved these changes

2024-02-26 23:34 UTC, ErikCald approved these changes

2024-02-26 23:40 UTC, weizhang-2706 approved these changes

2024-02-26 23:41 UTC, merged